export const ASCENDENT_NAME = "ASCENDENT_NAME"
export const DESCENDENT_NAME = "DESCENDENT_NAME"
export const ASCENDENT_ATTACK = "ASCENDENT_ATTACK"
export const DESCENDENT_ATTACK = "DESCENDENT_ATTACK"

