export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_TYPES = 'GET_TYPES';
export const POST_POKEMONS = 'POST_POKEMONS';
export const SET_STATE_PAGES = 'SET_STATE_PAGES';
export const FILTER_TYPES = 'FILTER_TYPES';
export const FILTER_CREATED = 'FILTER_CREATED';
export const GET_NAME_POKEMONS = 'GET_NAME_POKEMONS';
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const SORT_POKEMONS_ATTACK = 'SORT_POKEMONS_ATTACK';


export const CLEAN_POKEMONS = 'CLEAN_POKEMONS';
export const CLEAN_POKEMON_DETAIL = 'CLEAN_POKEMON_DETAIL';
